# Generated by Django 2.2.5 on 2020-02-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naijadictionary', '0002_auto_20200215_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='d_o_b',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
