# Generated by Django 2.2.5 on 2020-02-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naijadictionary', '0003_auto_20200215_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='definition',
            name='example',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='definition',
            name='poster',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
