# Generated by Django 2.2.5 on 2020-02-19 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('naijadictionary', '0005_auto_20200219_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submited',
            name='post_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userinfo', to='naijadictionary.UserProfile'),
        ),
    ]
