# Generated by Django 2.2.5 on 2020-02-19 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('naijadictionary', '0006_auto_20200219_0721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submited',
            name='user_name',
        ),
        migrations.AlterField(
            model_name='submited',
            name='post_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userinfo', to='naijadictionary.UserProfile'),
        ),
    ]
