# Generated by Django 2.2.5 on 2020-02-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naijadictionary', '0007_auto_20200219_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='submited',
            name='user_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
